'use strict';

const { Guide } = require('../models');

let options = {};
if (process.env.NODE_ENV === 'production') {
  options.schema = process.env.SCHEMA;  // define your schema in options object
}

const guidesList = [
  {
    userId: 1,
    title: 'How to Care for Monsteras',
    description: 'Essential tips for nurturing healthy Monsteras at home',
    content: "<p>Monsteras, with their striking foliage, are popular houseplants known for their easy maintenance and vibrant appearance. Follow these simple care guidelines to keep your Monstera thriving.</p> <h2>1. Proper Watering</h2> <p>Ensure the soil is evenly moist but not waterlogged. Water when the top inch of soil feels dry to the touch, usually every 1-2 weeks. Adjust frequency based on humidity levels and season.</p> <h2>2. Adequate Lighting</h2> <p>Place your Monstera in bright, indirect sunlight to encourage healthy growth. Avoid direct sunlight, which can scorch the leaves. In low light conditions, growth may slow down.</p> <h2>3. Humidity Levels</h2> <p>Monsteras prefer high humidity environments. Mist the leaves regularly or place a humidifier nearby, especially during dry seasons or in air-conditioned rooms.</p> <h2>4. Proper Drainage</h2> <p>Ensure your Monstera's pot has drainage holes to prevent waterlogging. Excess moisture can lead to root rot and other fungal diseases.</p> <h2>5. Temperature and Environment</h2> <p>Maintain a warm environment with temperatures between 65-85°F (18-30°C). Protect your Monstera from drafts and sudden temperature changes.</p> <h2>6. Fertilization</h2> <p>Feed your Monstera with a balanced, water-soluble fertilizer during the growing season (spring and summer) to promote lush foliage. Follow package instructions for proper dilution and frequency.</p> <h2>7. Pruning and Maintenance</h2> <p>Regularly prune your Monstera to encourage bushy growth and remove any damaged or yellowing leaves. Use clean, sharp scissors to make clean cuts.</p> <h2>8. Potting and Repotting</h2> <p>Choose a well-draining potting mix and repot your Monstera every 1-2 years or when the roots outgrow the container. Select a pot that's slightly larger than the current one.</p>"
  },
  {
    userId: 11,
    title: 'Top 5 Pet-Friendly Plants',
    description: 'A list of pet-friendly plants, from the ultimate pet and plant lover!',
    content: "<h2>1. Spider Plant</h2> <p>The Spider Plant is safe for cats and dogs. Its lush foliage adds a touch of green to your space, and it's easy to care for, thriving in a variety of light conditions.</p> <h2>2. Boston Fern</h2> <p>Boston Ferns are non-toxic to pets and help purify the air. They enjoy high humidity, making them ideal for bathrooms or kitchens with indirect sunlight.</p> <h2>3. Areca Palm</h2> <p>The Areca Palm is safe for pets and adds a tropical vibe to your home. Place it in a well-lit spot and water regularly to keep it healthy and vibrant.</p> <h2>4. Calathea</h2> <p>Calatheas are pet-friendly and come in various colorful patterns. These low-light plants thrive in indirect sunlight and prefer consistently moist soil.</p>  <h2>5. Friendship Plant (Pilea)</h2> <p>The Friendship Plant is safe for pets and features unique coin-shaped leaves. It's easy to propagate and makes an excellent addition to your indoor garden.</p><p>These pet-friendly plants not only enhance your living space but also provide a safe and soothing environment for your furry companions.</p>"
  },
  {
    userId: 3,
    title: 'How to Keep Pests Away',
    description: 'Learn how to tell pests: "Pests, no pesting!"',
    content: "<h2>1. Maintain Cleanliness</h2> <p>Regularly clean your living spaces and remove food debris, crumbs, and spills. Keep trash cans sealed and dispose of garbage promptly to deter pests.</p> <h2>2. Seal Entry Points</h2> <p>Inspect your home for gaps, cracks, and openings where pests can enter. Seal any entry points with caulk or weather stripping to prevent access.</p> <h2>3. Remove Standing Water</h2> <p>Eliminate sources of standing water, such as clogged gutters, leaky faucets, or stagnant ponds, as they attract pests like mosquitoes and rodents.</p> <h2>4. Store Food Properly</h2> <p>Keep food stored in airtight containers to prevent pests from accessing it. Store pet food securely and clean up spills promptly.</p> <h2>5. Use Natural Repellents</h2> <p>Consider using natural repellents like essential oils (e.g., peppermint, lavender) or plants (e.g., marigolds, basil) to deter pests. Place them strategically around your home and garden.</p> <h2>6. Maintain Outdoor Spaces</h2> <p>Keep outdoor areas tidy by trimming vegetation, removing debris, and storing firewood away from your home. Regularly inspect plants for signs of pest infestations.</p> <h2>7. Implement Integrated Pest Management (IPM)</h2> <p>Use a combination of preventive measures, cultural practices, and environmentally friendly pest control methods to manage pest populations effectively.</p> <h2>8. Seek Professional Help</h2> <p>If pest problems persist despite your efforts, consider consulting with pest control professionals. They can assess the situation and recommend appropriate treatment options.</p>"
  },
  {
    userId: 13,
    title: 'Understanding Lighting for Plants',
    description: 'Learn about the different types of light',
    content: "<h2>1. Natural Light</h2> <p>Natural light is the preferred light source for most plants. Place your plants near windows where they can receive indirect sunlight. South-facing windows generally provide the brightest light, while north-facing windows offer softer, more diffused light.</p> <h2>2. Direct Sunlight</h2> <p>Some plants thrive in direct sunlight, but too much can cause leaf burn. Monitor your plants closely and provide shading if necessary, especially during the intense afternoon sun.</p> <h2>3. Indirect Light</h2> <p>Many indoor plants prefer indirect light, which is gentler and less likely to cause damage. This type of light can be achieved by placing plants a few feet away from windows or using sheer curtains to filter sunlight.</p> <h2>4. Artificial Light</h2> <p>Supplemental lighting, such as fluorescent, LED, or grow lights, can be used to provide consistent light levels for plants, especially in areas with limited natural light. Position lights close to plants and adjust the duration and intensity based on plant requirements.</p><h2>5. Light Duration</h2><p>Most plants require around 12-16 hours of light per day for optimal growth. Use timers to ensure consistent light cycles and prevent overexposure or underexposure to light.</p><h2>6. Light Spectrum</h2> <p>Plants utilize different parts of the light spectrum for various stages of growth. Blue light promotes vegetative growth, while red light stimulates flowering and fruiting. Choose lights with appropriate spectrums or use full-spectrum bulbs for overall plant health.</p>"
  },
  {
    userId: 24,
    title: 'Different Soil Mixes for Plants',
    description: 'Explore various soil mixes tailored to different plant needs',
    content: "<h2>1. All-Purpose Potting Mix</h2><p>An all-purpose potting mix is suitable for most houseplants and outdoor container gardens. It typically consists of a blend of peat moss, perlite, and vermiculite, providing good drainage and aeration for healthy root development.</p><h2>2. Cactus/Succulent Mix</h2><p>A cactus or succulent mix is well-draining and sandy, mimicking the arid conditions these plants thrive in. It usually contains a mix of potting soil, sand, and perlite to prevent root rot and promote water drainage.</p><h2>3. Orchid Mix</h2><p>An orchid mix is designed to provide excellent drainage and aeration for orchid roots. It typically includes chunks of bark, charcoal, and perlite, allowing air to circulate around the roots while retaining moisture.</p><h2>4. Seed Starting Mix</h2><p>A seed starting mix is lightweight and fine-textured, making it ideal for germinating seeds. It often contains a blend of peat moss, vermiculite, and perlite, providing a sterile and moisture-retentive environment for seedlings.</p><h2>5. Acidic Soil Mix</h2><p>An acidic soil mix is formulated for acid-loving plants such as azaleas, rhododendrons, and blueberries. It typically contains peat moss, pine bark, and perlite, creating a slightly acidic pH level suitable for these plants.</p><p>Choose the right soil mix based on your plant's specific needs and enjoy watching them thrive in their optimal growing conditions.</p>"
  },
  {
    userId: 1,
    title: 'Caring for Plants in Winter',
    description: 'Learn how to protect your plants during the winter months',
    content: "<h2>1. Adjust Watering</h2><p>Reduce watering frequency during winter as plants tend to require less water. Check the soil moisture regularly and water only when the top inch of soil feels dry.</p><h2>2. Monitor Temperature</h2><p>Keep an eye on indoor and outdoor temperatures, as extreme cold can damage plants. Move potted plants away from drafty windows or doors, and consider insulating outdoor plants with frost cloth or mulch.</p><h2>3. Increase Humidity</h2><p>Indoor heating systems can reduce humidity levels, which may negatively impact plants. Increase humidity around indoor plants by using a humidifier, placing trays of water near them, or misting the leaves regularly.</p> <h2>4. Provide Adequate Light</h2><p>Winter days are shorter, resulting in less natural light for plants. Move indoor plants closer to windows to maximize sunlight exposure, and consider supplementing with artificial grow lights if needed.</p><h2>5. Protect from Frost</h2> <p>Outdoor plants are vulnerable to frost damage during winter. Cover tender plants with frost blankets or bring them indoors during freezing temperatures. Mulch around the base of plants to insulate roots and retain soil warmth.</p><h2>6. Prune Carefully</h2><p>Prune dormant plants sparingly during winter to remove dead or damaged branches. Avoid heavy pruning, as it can stimulate new growth that may be susceptible to frost damage.</p><h2>7. Reduce Fertilization</h2><p>Plants typically enter a period of dormancy in winter, so they require less fertilization. Limit fertilizing to once every 4-6 weeks or follow specific plant requirements for winter feeding.</p><h2>8. Watch for Pests</h2><p>Pests may seek shelter in warm indoor environments during winter. Monitor plants closely for signs of pest infestation, such as yellowing leaves or sticky residue, and treat as necessary with insecticidal soap or horticultural oil.</p>"
  },
  {
    userId: 2,
    title: 'Different Types of Plant Pots',
    description: 'Find the perfect pot for your plants',
    content: "<ul><li><h2>Terracotta Pots</h2><p>Classic clay pots with a rustic appearance. They provide good drainage but may dry out quickly.</p></li> <li><h2>Plastic Pots</h2><p>Durable and lightweight, plastic pots are affordable and come in various sizes and colors. They retain moisture well.</p></li><li><h2>Ceramic Pots</h2><p>Elegant and decorative, ceramic pots add style to indoor spaces. They can be glazed or unglazed and may require additional drainage holes.</p></li><li><h2>Fiberglass Pots</h2><p>Modern and lightweight, fiberglass pots are weather-resistant and suitable for outdoor use. They come in a variety of shapes and finishes.</p> </li><li><h2>Wooden Pots</h2><p>Natural and eco-friendly, wooden pots provide excellent insulation for plant roots. They may require lining to prevent rot.</p></li> <li> <h2>Hanging Baskets</h2><p>Perfect for trailing plants, hanging baskets are suspended from hooks or brackets. They come in various materials, including plastic, wire, and wicker.</p> </li><li><h2>Terra Cotta Planters</h2><p>Distinctive for their red-orange color, terra cotta planters are made from baked clay. They are porous, allowing for good air circulation.</p> </li><li><h2>Self-Watering Pots</h2> <p>These pots feature a reservoir at the bottom that automatically waters the plant. They are convenient for busy gardeners or plants with specific moisture needs.</p> </li></ul>"
  },
  {
    userId: 5,
    title: 'Tips for Plant Care Organization',
    description: 'Stay on top of your plant care with ease',
    content: "<h2>1. Use a Calendar or Planner</h2><p>Designate specific days for watering, fertilizing, pruning, and other plant care tasks on your calendar or planner. Set reminders to stay on track.</p><h2>2. Create a Plant Care Schedule</h2><p>Compile a plant care schedule listing each plant, its watering frequency, fertilization needs, and any other care requirements. Refer to this schedule regularly.</p><h2>3. Utilize Plant Care Apps</h2> <p>Download plant care apps that allow you to input your plant collection and set watering reminders. Some apps even provide care tips and personalized recommendations.</p> <h2>4. Label Watering Cans or Bottles</h2> <p>Label watering cans or bottles with the names of the plants they are intended for and the frequency of watering. This prevents confusion and ensures each plant receives the right amount of water.</p> <h2>5. Group Plants by Watering Needs</h2><p>Arrange your plants into groups based on their watering requirements (e.g., low, medium, high). This makes it easier to water them according to their needs and prevents over or under-watering.</p><h2>6. Invest in Self-Watering Systems</h2><p>Consider using self-watering systems such as water globes, drip irrigation, or capillary mats. These systems can help maintain consistent moisture levels in your plant pots, reducing the need for manual watering.</p> <h2>7. Keep Notes on Plant Progress</h2> <p>Keep a journal or digital notes documenting your plant care activities, observations, and any changes in plant health. This allows you to track progress and adjust your care routine accordingly.</p> <h2>8. Stay Consistent and Observant</h2><p>Consistency is key to successful plant care. Make it a habit to check your plants regularly for signs of stress, pests, or disease, and adjust your care routine as needed.</p>"
  },
  {
    userId: 15,
    title: 'How to Propagate Plants',
    description: 'Turn your plants into multiple plant babies!',
    content: "<h2>1. Stem Cutting</h2><p>Choose a healthy stem from the parent plant and cut it at a 45-degree angle just below a node. Remove lower leaves and place the cutting in water or moist soil. Keep it in a warm, bright location until roots develop.</p><h2>2. Leaf Cutting</h2><p>Select a healthy leaf from the parent plant and cut it cleanly from the stem. Place the leaf on top of moist soil or in water, ensuring the cut end makes contact with the growing medium. Roots will emerge from the cut end, eventually forming a new plant.</p><h2>3. Division</h2><p>For plants with multiple stems or offshoots (e.g., spider plants, aloe vera), carefully separate the individual sections using a clean knife or shears. Plant each division in its own pot with well-draining soil and water thoroughly.</p><h2>4. Layering</h2><p>Encourage plants with flexible stems (e.g., philodendrons, pothos) to form roots while still attached to the parent plant. Bend a stem gently to the ground and bury a portion of it in soil, keeping the tip above the surface. Roots will develop at the buried section, and once established, the new plant can be separated from the parent.</p><h2>5. Seed Propagation</h2><p>Collect seeds from mature plants and sow them in a suitable growing medium. Provide adequate moisture and warmth, and monitor seedlings as they emerge and grow. Transplant seedlings into individual pots once they develop true leaves.</p> <p>Experiment with different propagation methods to expand your plant collection and share the joy of gardening with others.</p>"
  },
  {
    "userId": 5,
    "title": "Choosing Low-Light Plants",
    "description": "Discover the best plants for low-light spaces.",
    "content": "<h2>1. Understanding Low-Light Conditions</h2><p>Low-light conditions are typically found in rooms that do not receive direct sunlight. These spaces can still support various houseplants that are adapted to lower light levels.</p><h2>2. Best Low-Light Plants</h2><ul><li><strong>Snake Plant:</strong> Hardy and adaptable, perfect for dim corners.</li><li><strong>ZZ Plant:</strong> Tolerates neglect and low light.</li><li><strong>Pothos:</strong> Thrives in low-light and is easy to care for.</li><li><strong>Peace Lily:</strong> Beautiful and low-light tolerant.</li></ul><h2>3. Care Tips</h2><p><em>Watering:</em> Low-light plants typically require less frequent watering. Allow the soil to dry out between waterings.</p><p><em>Fertilizing:</em> Feed sparingly, as these plants grow slower.</p><p><em>Pruning:</em> Regularly remove dead or yellowing leaves to promote health.</p><p>Choosing the right low-light plants can enhance the greenery in your home without the need for bright, direct sunlight.</p>"
  },
  {
    userId: 17,
    title: "Caring for Succulents",
    description: "Tips for healthy succulent care.",
    content: "<h2>Introduction to Succulent Care</h2><p>Succulents are popular for their unique appearance and low maintenance. This guide will help you understand how to care for succulents and keep them thriving.</p><h2>Choosing the Right Succulents</h2><p>Select succulents that suit your indoor environment. Some popular choices include Echeveria, Aloe Vera, and Jade Plant. Make sure to choose healthy plants with firm, vibrant leaves.</p><h2>Planting Succulents</h2><ul><li><strong>Containers:</strong> Use pots with drainage holes to prevent water buildup.</li><li><strong>Soil:</strong> Use a well-draining succulent or cactus mix.</li><li><strong>Location:</strong> Place your succulents in a bright spot with indirect sunlight.</li></ul><h2>Watering Succulents</h2><p>Watering succulents properly is crucial. Allow the soil to dry out completely between waterings. When watering, soak the soil thoroughly and let excess water drain out. Avoid getting water on the leaves to prevent rot.</p><h2>Light and Temperature</h2><p>Succulents need plenty of light to thrive. Place them in a location where they receive bright, indirect sunlight for at least 6 hours a day. Maintain a temperature range between 60-80°F (15-27°C).</p><h2>Fertilizing Succulents</h2><p>Feed your succulents with a diluted, balanced fertilizer during the growing season (spring and summer). Fertilize once a month to promote healthy growth.</p><h2>Common Issues and Solutions</h2><ul><li><strong>Overwatering:</strong> Signs include yellowing leaves and mushy stems. Allow the soil to dry out completely before watering again.</li><li><strong>Underwatering:</strong> Succulents will have wrinkled, shriveled leaves. Water thoroughly and adjust your watering schedule.</li><li><strong>Pests:</strong> Look out for pests like mealybugs and spider mites. Treat with insecticidal soap or neem oil if needed.</li></ul><h2>Propagation</h2><p>Propagate succulents through leaf or stem cuttings. Allow cuttings to dry and callous over before planting in well-draining soil. Keep them in a bright, warm spot until roots develop.</p><p>With these care tips, your succulents will thrive and add beauty to your home. Enjoy your succulent gardening journey!</p>"
  },
  {
    userId: 12,
    title: "Air Purifying Plants",
    description: "Best plants for air purification.",
    content: "<h2>Introduction to Air Purifying Plants</h2><p>Indoor plants not only add beauty to your home but also help purify the air. This guide highlights the best air purifying plants and how to care for them.</p><h2>Top Air Purifying Plants</h2><ul><li><strong>Snake Plant (Sansevieria):</strong> Removes toxins like formaldehyde and benzene. Low maintenance and thrives in low light.</li><li><strong>Spider Plant (Chlorophytum comosum):</strong> Effective at removing carbon monoxide and xylene. Easy to grow and propagate.</li><li><strong>Peace Lily (Spathiphyllum):</strong> Removes mold spores from the air. Prefers indirect light and regular watering.</li><li><strong>English Ivy (Hedera helix):</strong> Reduces airborne fecal matter particles and filters out formaldehyde. Needs bright, indirect light and moist soil.</li><li><strong>Aloe Vera:</strong> Known for its medicinal properties, it also removes formaldehyde and benzene. Requires bright light and minimal watering.</li></ul><h2>Caring for Air Purifying Plants</h2><p>Proper care is essential to keep these plants healthy and effective at purifying the air. Here are some general care tips:</p><ul><li><strong>Light:</strong> Most air purifying plants prefer bright, indirect light. Avoid direct sunlight as it can scorch the leaves.</li><li><strong>Watering:</strong> Water your plants when the top inch of soil feels dry. Be careful not to overwater, as this can lead to root rot.</li><li><strong>Humidity:</strong> Many air purifying plants thrive in humid environments. Increase humidity by misting the leaves or using a humidifier.</li><li><strong>Fertilizing:</strong> Feed your plants with a balanced, water-soluble fertilizer every 4-6 weeks during the growing season.</li></ul><h2>Placement Tips</h2><p>Strategically place your air purifying plants in areas where you spend the most time. This includes living rooms, bedrooms, and home offices. Group plants together to create a mini indoor jungle, enhancing both aesthetics and air quality.</p><h2>Conclusion</h2><p>By incorporating air purifying plants into your home, you can enjoy cleaner air and a more pleasant living environment. Choose the right plants for your space and provide them with the care they need to thrive.</p>"
  },
  {
    "userId": 8,
    "title": "DIY Terrariums",
    "description": "Create your own mini ecosystem.",
    "content": "<h2>Introduction to DIY Terrariums</h2><p>Terrariums are easy to create and maintain. This guide walks you through building your own.</p><h2>Materials Needed</h2><ul><li>Glass container with lid</li><li>Small pebbles</li><li>Activated charcoal</li><li>Potting soil</li><li>Moss</li><li>Small plants</li><li>Decorative elements</li></ul><h2>Step-by-Step Instructions</h2><h3>1. Choose Your Container</h3><p>Select a clear glass container.</p><h3>2. Create a Drainage Layer</h3><p>Add pebbles at the bottom for drainage.</p><h3>3. Add Activated Charcoal</h3><p>Sprinkle a thin layer of charcoal over the pebbles.</p><h3>4. Add Potting Soil</h3><p>Add a layer of soil deep enough for plant roots.</p><h3>5. Plant Your Terrarium</h3><p>Plant your chosen plants, arranging them with space to grow.</p><h3>6. Add Moss and Decorative Elements</h3><p>Cover soil with moss and add decorations.</p><h3>7. Water and Close the Lid</h3><p>Mist plants, close the lid, and maintain humidity.</p><h2>Care and Maintenance</h2><ul><li><strong>Light:</strong> Bright, indirect light.</li><li><strong>Watering:</strong> Minimal watering needed.</li><li><strong>Pruning:</strong> Trim dead or overgrown leaves.</li></ul><h2>Conclusion</h2><p>DIY terrariums are fun and rewarding, bringing nature into your home.</p>"
  },
  {
    "userId": 22,
    "title": "Indoor Plant Arrangements",
    "description": "Create stunning indoor plant displays.",
    "content": "<h2>Introduction to Indoor Plant Arrangements</h2><p>Add beauty and tranquility to your home with stunning plant displays.</p><h2>Choosing the Right Plants</h2><p>Combine plants that complement each other in size, color, and care needs.</p><ul><li><strong>Fiddle Leaf Fig:</strong> Tall and dramatic.</li><li><strong>Peace Lily:</strong> Elegant with white blooms.</li><li><strong>Pothos:</strong> Lush and cascading.</li><li><strong>Succulents:</strong> Unique shapes and colors.</li><li><strong>Spider Plant:</strong> Great for hanging baskets.</li></ul><h2>Designing Your Arrangement</h2><p>Consider height, color, and texture.</p><ul><li><strong>Height and Layering:</strong> Use plants of varying heights.</li><li><strong>Color and Texture:</strong> Mix leaf colors and textures.</li><li><strong>Containers:</strong> Choose pots that complement your decor.</li><li><strong>Grouping:</strong> Group plants in odd numbers for a natural look.</li></ul><h2>Placement and Care</h2><p>Proper placement and care are crucial.</p><ul><li><strong>Light:</strong> Ensure adequate light for each plant.</li><li><strong>Watering:</strong> Water according to each plant's needs.</li><li><strong>Humidity:</strong> Maintain humidity with misting or a humidifier.</li><li><strong>Pruning and Maintenance:</strong> Regularly prune and dust leaves.</li></ul><h2>Conclusion</h2><p>Indoor plant arrangements enhance your living space with thoughtful design and care.</p>"
  },
  {
    "userId": 12,
    "title": "Repotting Your Houseplants",
    "description": "Step-by-step guide to repotting your plants.",
    "content": "<h2>1. When to Repot</h2><p>Repotting is necessary when plants outgrow their pots, show signs of being root-bound, or if the soil is depleted.</p><h2>2. Choosing a New Pot</h2><ul><li><strong>Size:</strong> Select a pot 1-2 inches larger in diameter than the current pot.</li><li><strong>Material:</strong> Consider clay, plastic, or ceramic based on plant needs.</li><li><strong>Drainage:</strong> Ensure the pot has drainage holes to prevent waterlogging.</li></ul><h2>3. Repotting Steps</h2><ol><li>Water the plant a day before repotting.</li><li>Remove the plant gently from its current pot.</li><li>Loosen the root ball and trim any dead roots.</li><li>Place the plant in the new pot and fill with fresh soil.</li><li>Water thoroughly and let it settle.</li></ol><p>Regular repotting promotes healthy growth and revitalizes your houseplants.</p>"
  },
  {
    "userId": 19,
    "title": "Watering Techniques for Plants",
    "description": "Learn the best watering practices for houseplants.",
    "content": "<h2>1. Understanding Plant Needs</h2><p>Different plants have varying water requirements based on their species, size, and environment.</p><h2>2. Types of Watering</h2><ul><li><strong>Top Watering:</strong> Watering from above, ensuring the entire soil is moistened.</li><li><strong>Bottom Watering:</strong> Placing the pot in a tray of water to allow the soil to absorb moisture from the bottom.</li><li><strong>Misting:</strong> Spraying leaves with water, beneficial for humidity-loving plants.</li></ul><h2>3. Tips for Effective Watering</h2><p><em>Consistency:</em> Water on a regular schedule but adjust based on plant needs.</p><p><em>Soil Check:</em> Check soil moisture before watering to avoid overwatering.</p><p><em>Quality:</em> Use room-temperature, filtered water to prevent mineral buildup.</p><p>Proper watering is crucial for plant health, preventing both overwatering and underwatering.</p>"
  },
  {
    "userId": 23,
    "title": "Fertilizing Houseplants",
    "description": "Essential guide to feeding your indoor plants.",
    "content": "<h2>1. Why Fertilize?</h2><p>Fertilizers provide essential nutrients that may not be available in potting soil, promoting growth and vitality.</p><h2>2. Types of Fertilizers</h2><ul><li><strong>Liquid Fertilizers:</strong> Easy to apply and quickly absorbed.</li><li><strong>Granular Fertilizers:</strong> Slow-release options that provide steady nutrients.</li><li><strong>Organic Fertilizers:</strong> Derived from natural sources, enhancing soil health.</li></ul><h2>3. How to Apply</h2><ol><li>Read the instructions on the fertilizer package.</li><li>Apply at the base of the plant, avoiding leaves.</li><li>Water thoroughly after fertilizing to help absorption.</li></ol><p><em>Frequency:</em> Typically, fertilize every 4-6 weeks during the growing season.</p><p>Regular fertilization helps maintain healthy and vibrant houseplants.</p>"
  },
  {
    "userId": 7,
    "title": "Choosing the Right Plant for Beginners",
    "description": "Best houseplants for novice gardeners.",
    "content": "<h2>1. Easy-Care Plant Varieties</h2><p>Beginner-friendly plants are low-maintenance and forgiving of minor care mistakes.</p><h2>2. Recommended Plants</h2><ul><li><strong>Spider Plant:</strong> Resilient and adapts well to various conditions.</li><li><strong>Philodendron:</strong> Tolerates low light and irregular watering.</li><li><strong>Aloe Vera:</strong> Requires minimal water and thrives in bright light.</li><li><strong>Jade Plant:</strong> A sturdy succulent that needs little water.</li></ul><h2>3. Basic Care Tips</h2><p><em>Light:</em> Ensure adequate but not excessive light.</p><p><em>Water:</em> Water only when the soil is dry to the touch.</p><p><em>Soil:</em> Use well-draining soil mixes suitable for each plant type.</p><p>Starting with these easy-care plants can help build confidence and experience in plant care.</p>"
  },
  {
    "userId": 2,
    "title": "Preventing Root Rot",
    "description": "Tips to avoid and treat root rot in plants.",
    "content": "<h2>1. Causes of Root Rot</h2><p>Root rot is caused by overwatering and poor drainage, leading to fungal growth.</p><h2>2. Signs of Root Rot</h2><ul><li>Yellowing leaves</li><li>Mushy, blackened roots</li><li>Stunted growth</li></ul><h2>3. Prevention Tips</h2><p><em>Proper Drainage:</em> Ensure pots have drainage holes.</p><p><em>Watering:</em> Allow soil to dry between waterings.</p><p><em>Soil Choice:</em> Use well-draining potting mixes.</p><h2>4. Treatment Steps</h2><ol><li>Remove the plant from the pot and wash off the soil.</li><li>Trim away affected roots.</li><li>Repot in fresh, dry soil.</li><li>Reduce watering frequency.</li></ol><p>Preventing root rot involves proper watering practices and ensuring good soil drainage.</p>"
  },
  {
    "userId": 25,
    "title": "Houseplant Pest Identification",
    "description": "Identify and manage common houseplant pests.",
    "content": "<h2>1. Common Pests</h2><p>Several pests can affect houseplants, each requiring different management strategies.</p><h2>2. Identifying Pests</h2><ul><li><strong>Aphids:</strong> Small, green or black insects found on new growth.</li><li><strong>Spider Mites:</strong> Tiny, red or yellow dots on leaves, often with webbing.</li><li><strong>Mealybugs:</strong> White, cottony masses on stems and leaves.</li><li><strong>Scale:</strong> Brown, shell-like insects on stems and undersides of leaves.</li></ul><h2>3. Treatment Methods</h2><ol><li>Remove pests manually with a damp cloth or by pruning affected areas.</li><li>Use insecticidal soap or neem oil sprays.</li><li>Isolate affected plants to prevent the spread of pests.</li><li>Introduce beneficial insects like ladybugs for natural pest control.</li></ol><p>Regular monitoring and early intervention can keep pest populations under control and protect your houseplants.</p>"
  },
  {
    "userId": 10,
    "title": "Indoor Plant Pruning Basics",
    "description": "Learn how to prune houseplants effectively.",
    "content": "<h2>1. Importance of Pruning</h2><p>Pruning helps maintain plant health, encourages new growth, and keeps plants looking their best.</p><h2>2. When to Prune</h2><p>Prune during the plant's active growing season, typically spring and summer, to encourage new growth.</p><h2>3. Pruning Tools</h2><ul><li><strong>Pruning Shears:</strong> For larger stems and branches.</li><li><strong>Scissors:</strong> For smaller, delicate stems.</li><li><strong>Disinfectant:</strong> To clean tools between cuts and prevent disease spread.</li></ul><h2>4. Pruning Techniques</h2><ol><li>Identify dead, damaged, or diseased parts and remove them first.</li><li>Trim back leggy growth to promote bushiness.</li><li>Cut just above a leaf node to encourage new shoots.</li><li>Remove spent flowers to direct energy to new growth.</li></ol><p>Regular pruning keeps your houseplants healthy and promotes fuller, more vibrant growth.</p>"
  },
  {
    "userId": 4,
    "title": "Dealing with Plant Diseases",
    "description": "Identify and treat common houseplant diseases.",
    "content": "<h2>1. Common Plant Diseases</h2><p>Houseplants can suffer from various diseases, often caused by fungi, bacteria, or viruses.</p><h2>2. Identifying Diseases</h2><ul><li><strong>Powdery Mildew:</strong> White, powdery spots on leaves.</li><li><strong>Root Rot:</strong> Mushy, discolored roots due to overwatering.</li><li><strong>Leaf Spot:</strong> Brown or black spots on leaves.</li><li><strong>Botrytis Blight:</strong> Gray mold on flowers and leaves.</li></ul><h2>3. Prevention Methods</h2><p><em>Watering:</em> Avoid overwatering and water at the base of the plant.</p><p><em>Air Circulation:</em> Ensure good airflow around plants.</p><p><em>Cleanliness:</em> Remove dead leaves and debris from soil surface.</p><h2>4. Treatment Options</h2><ol><li>Isolate affected plants to prevent spreading.</li><li>Remove and dispose of affected plant parts.</li><li>Use appropriate fungicides or bactericides as needed.</li><li>Ensure proper care practices to prevent recurrence.</li></ol><p>Understanding and addressing plant diseases early can save your houseplants from severe damage.</p>"
  },
  {
    "userId": 16,
    "title": "Houseplant Watering Schedule",
    "description": "Create an effective watering schedule for plants.",
    "content": "<h2>1. Importance of a Watering Schedule</h2><p>Consistent watering helps maintain plant health and prevents over- or under-watering.</p><h2>2. Factors Affecting Watering Frequency</h2><ul><li><strong>Plant Type:</strong> Different plants have varying water needs.</li><li><strong>Season:</strong> Plants typically need more water during the growing season.</li><li><strong>Environment:</strong> Humidity and temperature affect water needs.</li></ul><h2>3. Creating a Schedule</h2><ol><li>Research each plant's specific water requirements.</li><li>Group plants with similar needs together.</li><li>Use a calendar or app to track watering days.</li><li>Adjust frequency based on seasonal changes and plant observations.</li></ol><h2>4. Monitoring Soil Moisture</h2><p>Check soil moisture regularly using a moisture meter or by feeling the soil. Adjust the schedule as needed based on the plant's response.</p><p>Creating and following a watering schedule helps ensure your houseplants receive the right amount of water for optimal health.</p>"
  },
  {
    "userId": 10,
    "title": "Carnivorous Houseplants Guide",
    "description": "Tips for growing carnivorous houseplants.",
    "content": "<h2>Introduction to Carnivorous Houseplants</h2><p>Carnivorous plants are fascinating and unique. They capture and digest insects to gain nutrients. This guide provides tips on growing and caring for these intriguing plants.</p><h2>Popular Carnivorous Houseplants</h2><ul><li><strong>Venus Flytrap (Dionaea muscipula):</strong> Known for its jaw-like traps.</li><li><strong>Pitcher Plant (Sarracenia, Nepenthes):</strong> Features deep, liquid-filled pitchers.</li><li><strong>Sun Dew (Drosera):</strong> Covered in sticky, dew-like droplets.</li><li><strong>Butterwort (Pinguicula):</strong> Leaves are sticky and trap small insects.</li></ul><h2>Growing Conditions</h2><p>Carnivorous plants have specific growing needs:</p><ul><li><strong>Light:</strong> Bright, indirect light. Some species tolerate direct sunlight.</li><li><strong>Soil:</strong> Use a mix of sphagnum moss and perlite. Avoid regular potting soil.</li><li><strong>Water:</strong> Use distilled or rainwater. Keep soil consistently moist but not waterlogged.</li><li><strong>Humidity:</strong> High humidity levels are preferred. Consider using a humidity tray or misting the plants regularly.</li></ul><h2>Feeding Your Carnivorous Plants</h2><p>While carnivorous plants can catch their own food, you can supplement their diet:</p><ul><li><strong>Insects:</strong> Feed them small, live insects such as flies or ants.</li><li><strong>Frequency:</strong> Feed them once every 1-2 weeks during the growing season.</li></ul><h2>Common Issues and Solutions</h2><ul><li><strong>Blackened Traps:</strong> Overfeeding or poor water quality. Use distilled water and feed sparingly.</li><li><strong>Mold:</strong> Ensure good air circulation and avoid overwatering.</li><li><strong>Poor Growth:</strong> Check light levels and soil conditions. Adjust as needed.</li></ul><h2>Repotting and Propagation</h2><p>Repot your plants every 1-2 years in fresh soil mix:</p><ul><li><strong>Timing:</strong> Best done in early spring.</li><li><strong>Method:</strong> Gently remove the plant from its pot, shake off old soil, and place it in new soil mix.</li><li><strong>Propagation:</strong> Many carnivorous plants can be propagated through leaf cuttings or division.</li></ul><h2>Conclusion</h2><p>Growing carnivorous houseplants can be a rewarding hobby. With the right care, these unique plants will thrive and provide a captivating addition to your indoor garden.</p>"
  }

]
/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    try {
      await Guide.bulkCreate(guidesList, { validate: true })
    } catch (err) {
      console.error(err);
      throw err;
    }
  },

  async down(queryInterface, Sequelize) {
    options.tableName = 'Guides';
    const Op = Sequelize.Op;
    return queryInterface.bulkDelete(options, { [Op.or]: guidesList }, {});
  }
};
